<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik' ? 'active' : '') ?>" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" role="tab" aria-controls="vert-tabs-home" aria-selected="true">A. Riwayat Pribadi</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik2' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik2&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">B. Riwayat Ortu</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik3' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik3&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">C. Pemeriksaan</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik4' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik4&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">D. Mata</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik5' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik5&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">E. THT-KL</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik6' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik6&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">F. Thorax</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik7' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik7&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">G. Paru</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik8' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik8&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">H. Jantung</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik9' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik9&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">I. Abdomen</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik10' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik10&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">J. Urogenital</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik11' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik11&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">K. Ekstrimitas</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik12' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik12&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">L. Psikiatri</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik13' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik13&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">M. Gigi</a>
<a class="nav-link <?php echo ($_GET['act'] == 'ass_fisik14' ? 'active' : '') ?>" id="vert-tabs-profile-tab" data-toggle="" href="<?php echo base_url('medcheck/tambah.php?act=ass_fisik14&id=' . $this->input->get('id'). '&id_ass='.$this->input->get('id_ass') . '&status=15') ?>" aria-controls="vert-tabs-profile" aria-selected="false">N. Syaraf</a>